# Generated by Django 4.1.3 on 2022-12-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
