# Generated by Django 4.1.3 on 2022-12-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='active',
        ),
    ]
